Added DisplayName property in Volume section
ranjith-karunesh-hpe/ODIM pull request #1
Opened 2023-01-19 05:59 UTC by rnjtk

Added DisplayName property to Creating a Volume section in the API Readme

2023-01-19 08:20 UTC, sunithasomanna approved these changes

2023-01-20 06:32 UTC, amar-shalgar requested changes

2023-01-20 06:32 UTC, amar-shalgar commented on docs/README.md
> +   "DisplayName":"name1"
Please add Volume_Name instead of name1

2023-01-20 08:40 UTC, ranjith-karunesh-hpe commented on docs/README.md
> +   "DisplayName":"name1"
Fixed

2023-01-20 08:55 UTC, amar-shalgar approved these changes

2023-01-20 08:56 UTC, merged